/*
 * This file is generated by jOOQ.
 */
package com.xobotun.jooq.public_;


import com.xobotun.jooq.DefaultCatalog;
import com.xobotun.jooq.public_.tables.Product;
import com.xobotun.jooq.public_.tables.ProductRecommendation;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.product_recommendation</code>.
     */
    public final ProductRecommendation PRODUCT_RECOMMENDATION = ProductRecommendation.PRODUCT_RECOMMENDATION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Product.PRODUCT,
            ProductRecommendation.PRODUCT_RECOMMENDATION
        );
    }
}
