/*
 * This file is generated by jOOQ.
 */
package com.xobotun.jooq.public_;


import com.xobotun.jooq.public_.tables.Product;
import com.xobotun.jooq.public_.tables.ProductRecommendation;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>public.product_recommendation</code>.
     */
    public static final ProductRecommendation PRODUCT_RECOMMENDATION = ProductRecommendation.PRODUCT_RECOMMENDATION;
}
